#DB
spring:
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/blog
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#JPA

#Token
jwt:
  secret-key: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey

oauth:
  kakao:
    client-id: 0fB9uQkvgFlDAZzpWNkAH5Lq1SSX50ff
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: ErYDAhBaXu
    client-id: FFNzMrOpyZ5NHYps7b6b
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

